### ISSUE TITLE
In case of several elements within the same widget, callbacks seem to loose specificity

### ISSUE THREAD

**Issue by m-albert** [imjoy-team/kaibu#95]
I'm playing around with kaibu widgets in the context of a collaborative annotation tool and I'm loving it!

Also I stumbled upon what might be a bug: It seems that when having several elements as part of the same widget, elements can call the callbacks of other elements.

For example, when taking this example code from https://kaibu.org/docs/#/api?id=add_widgetoptions:

```python
from imjoy import api

class ImJoyPlugin():
    async def setup(self):
        pass

    async def run(self, ctx):
        viewer = await api.createWindow(src="https://kaibu.org/#/app")

        async def say_hello():
            await api.alert('Hello!')

        async def select_mode(mode):
            await api.alert("Selected mode: " + mode)

        await viewer.add_widget(
            {
                "_rintf": True,
                "name": "Control",
                "type": "control",
                "elements": [
                    {
                        "type": "button",
                        "label": "Say Hello",
                        "callback": say_hello,
                    },
                    {
                        "type": "dropdown",
                        "label": "Mode",
                        "options": ["Mode A", "Mode B"],
                        "callback": select_mode,
                    },
                ],
            })

api.export(ImJoyPlugin())
```

and pressing the button "Say Hello", no alert is shown. Instead, the java console reports the following, which suggests that `select_mode` was called instead of `say_hello`:
```
Error: Error: Traceback (most recent call last):
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ImJoyPlugin.run.<locals>.select_mode() missing 1 required positional argument: 'mode'
    at c._decode (rpc.js:787:19)
    at c._decode (rpc.js:831:35)
    at c._unwrap (rpc.js:863:23)
    at rpc.js:260:29
    at Connection._fire (utils.js:334:11)
    at Connection.handleEvent (pluginIframe.js:64:14)
```

I'm getting the same problem in other contexts. A workaround that works for me consists in placing buttons in separate widgets.

Thanks!

**Comment by m-albert** [comment]
Coming back to this issue, I found that assigning different `_rintf` to the different elements leads to expected behaviour.

Maybe sth goes wrong during encoding or decoding of the remote functions, e.g. functions are serialised identically?

This plugin definition works:
```python
from imjoy import api

class ImJoyPlugin():
    async def setup(self):
        pass

    async def run(self, ctx):
        viewer = await api.createWindow(src="https://kaibu.org/#/app")

        async def say_hello():
            await api.alert('Hello!')

        async def select_mode(mode):
            await api.alert("Selected mode: " + mode)

        await viewer.add_widget(
            {
                # "_rintf": True,
                "name": "Control",
                "type": "control",
                "elements": [
                    {
                        "type": "button",
                        "_rintf": "rintf1",
                        "label": "Say Hello",
                        "callback": say_hello,
                    },
                    {
                        "type": "dropdown",
                        "_rintf": "rintf2",
                        "label": "Mode",
                        "options": ["Mode A", "Mode B"],
                        "callback": select_mode,
                    },
                ],
            })

api.export(ImJoyPlugin())
```
